// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAaZK_20Cnfo4IL9UR9r_NYR0gMcf4KtQ',
    appId: '1:539922454956:web:0fa4101a4f57706fdf8209',
    messagingSenderId: '539922454956',
    projectId: 'myfiresttask',
    authDomain: 'myfiresttask.firebaseapp.com',
    storageBucket: 'myfiresttask.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYD-4e90ufHO0Mwlo2zs8R5dDDri4EtLI',
    appId: '1:539922454956:android:5c0aad926819d0dedf8209',
    messagingSenderId: '539922454956',
    projectId: 'myfiresttask',
    storageBucket: 'myfiresttask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyOgQKdpnFDYiHY_DtxPXD76F5SxIhbTE',
    appId: '1:539922454956:ios:50d2f9fd88eb4f14df8209',
    messagingSenderId: '539922454956',
    projectId: 'myfiresttask',
    storageBucket: 'myfiresttask.appspot.com',
    iosClientId: '539922454956-7t4jc72ec19movl166rt30uf8hqtul5o.apps.googleusercontent.com',
    iosBundleId: 'com.Abs.AI.authenticationTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyOgQKdpnFDYiHY_DtxPXD76F5SxIhbTE',
    appId: '1:539922454956:ios:50d2f9fd88eb4f14df8209',
    messagingSenderId: '539922454956',
    projectId: 'myfiresttask',
    storageBucket: 'myfiresttask.appspot.com',
    iosClientId: '539922454956-7t4jc72ec19movl166rt30uf8hqtul5o.apps.googleusercontent.com',
    iosBundleId: 'com.Abs.AI.authenticationTask',
  );
}
